---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world
    spec:
      automountServiceAccountToken: false
      containers:
        - name: hello-world
          image: harbor.apko.do-2021.fr/do4-2022/openstack-k0s-apko/hello-world:ee5ffa6
          imagePullPolicy: IfNotPresent
          env:
            - name: GIN_MODE
              value: "release"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
