---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
spec:
  serviceAccountName: helm-controller
  targetNamespace: kyverno
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: "3.1.4"
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 12h
  values:
    installCRDs: true
