---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configurations
spec:
  serviceAccountName: kustomize-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: openstack-k0s-apko
  path: infrastructure/configurations
  dependsOn:
    - name: infrastructure-controllers
