---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world-team
  namespace: hello-world-app
spec:
  interval: 5m
  path: apps/hello-world
  prune: false
  serviceAccountName: hello-world-team
  sourceRef:
    kind: GitRepository
    name: hello-world-team
