---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: hello-world-team
  name: hello-world-team
  namespace: hello-world-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    toolkit.fluxcd.io/tenant: hello-world-team
  name: hello-world-team-role
  namespace: hello-world-app
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: hello-world-team
  name: hello-world-team-reconciler
  namespace: hello-world-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hello-world-team-role
subjects:
  - kind: ServiceAccount
    name: hello-world-team
    namespace: hello-world-app
