---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: hello-world-team
  name: hello-world-team
  namespace: hello-world-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: hello-world-team
  name: hello-world-team-reconciler
  namespace: hello-world-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: gotk:hello-world-team:reconciler
  - kind: ServiceAccount
    name: hello-world-team
    namespace: hello-world-app
