---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world-team-tenant
spec:
  serviceAccountName: kustomize-controller
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: openstack-k0s-apko
  path: tenants/hello-world-team
  dependsOn:
    - name: infrastructure-controllers
    - name: infrastructure-configurations
