---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  serviceAccountName: helm-controller
  targetNamespace: harbor
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: "1.14.2"
      sourceRef:
        kind: HelmRepository
        name: harbor
      interval: 12h
  values:
    expose:
      type: ingress
      tls:
        enabled: true
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: cluster-issuer
        hosts:
          core: harbor.apko.do-2021.fr
    externalURL: https://harbor.apko.do-2021.fr
