apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - infrastructure/controllers.yaml
  - infrastructure/configurations.yaml
  - tenants/hello-world-team.yaml
