---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloud-controller-manager
spec:
  serviceAccountName: helm-controller
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: openstack-cloud-controller-manager
      version: "2.29.2"
      sourceRef:
        kind: HelmRepository
        name: cloud-controller-manager
      interval: 12h
  values:
    secret:
      enabled: true
      name: os-cloud-credentials
      create: false
    nodeSelector:
      node-role.kubernetes.io/control-plane: null
