---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  serviceAccountName: helm-controller
  targetNamespace: nginx
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 12h
