---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  serviceAccountName: helm-controller
  targetNamespace: cert-manager
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "1.14.4"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 12h
  values:
    installCRDs: true
